"""implemented coach table

Revision ID: 0e33b088ff70
Revises: fa3d2061d14e
Create Date: 2020-07-26 23:23:36.453128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e33b088ff70'
down_revision = 'fa3d2061d14e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach',
    sa.Column('coach_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('category', sa.String(length=6), nullable=False),
    sa.Column('symptom', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('questions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('advice', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('datetime_created', sa.DateTime(), nullable=False),
    sa.Column('datetime_last_modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('coach_id'),
    sa.UniqueConstraint('coach_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coach')
    # ### end Alembic commands ###
