"""add tire pressure JSON

Revision ID: 15032ce8b451
Revises: e109041b33dd
Create Date: 2020-12-29 11:56:55.493985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '15032ce8b451'
down_revision = 'e109041b33dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('rain_front_pressure', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('bike', sa.Column('rain_rear_pressure', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('bike', sa.Column('slick_front_pressure', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('bike', sa.Column('slick_rear_pressure', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bike', 'slick_rear_pressure')
    op.drop_column('bike', 'slick_front_pressure')
    op.drop_column('bike', 'rain_rear_pressure')
    op.drop_column('bike', 'rain_front_pressure')
    # ### end Alembic commands ###
