"""changed JSON field to ARRAY

Revision ID: 17a6500d4803
Revises: 4856916c3137
Create Date: 2021-01-02 00:58:01.136983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17a6500d4803'
down_revision = '4856916c3137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coach', 'questions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.String()),
               postgresql_using="string_to_array(translate(questions::text, '[] \"', ''), ',')::character varying[]",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coach', 'questions',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               postgresql_using="array_to_json(questions::character varying[])::json",
               existing_nullable=True)
    # ### end Alembic commands ###
