"""empty message

Revision ID: 19e2b2f7f1bf
Revises: 5139c11ad7fb
Create Date: 2020-06-12 16:48:51.203590

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19e2b2f7f1bf'
down_revision = '5139c11ad7fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training',
    sa.Column('training_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('weather', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('datetime_created', sa.DateTime(), nullable=False),
    sa.Column('datetime_last_modified', sa.DateTime(), nullable=False),
    sa.Column('datetime_display', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('training_id'),
    sa.UniqueConstraint('training_id')
    )
    op.create_table('setup',
    sa.Column('setup_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('training_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('bike_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('operating_hours', sa.Float(), nullable=False),
    sa.Column('weather', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('slick_pressure_front', sa.Float(), nullable=True),
    sa.Column('slick_pressure_rear', sa.Float(), nullable=True),
    sa.Column('rain_pressure_front', sa.Float(), nullable=True),
    sa.Column('rain_pressure_rear', sa.Float(), nullable=True),
    sa.Column('setup', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('datetime_created', sa.DateTime(), nullable=False),
    sa.Column('datetime_last_modified', sa.DateTime(), nullable=False),
    sa.Column('datetime_display', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bike_id'], ['bike.bike_id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['training.training_id'], ),
    sa.PrimaryKeyConstraint('setup_id'),
    sa.UniqueConstraint('setup_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setup')
    op.drop_table('training')
    # ### end Alembic commands ###
