"""changed JSON field to ARRAY

Revision ID: 4856916c3137
Revises: 59afd48d9690
Create Date: 2021-01-02 00:40:05.149943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4856916c3137'
down_revision = '59afd48d9690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('history', 'tags',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.String()),
               postgresql_using="string_to_array(translate(tags::text, '[] \"', ''), ',')::character varying[]",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('history', 'tags',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               postgresql_using="array_to_json(tags::character varying[])::json",
               existing_nullable=True)
    # ### end Alembic commands ###
