"""empty message

Revision ID: 5139c11ad7fb
Revises: 
Create Date: 2020-06-12 15:48:00.033512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5139c11ad7fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bike', ['bike_id'])
    op.create_unique_constraint(None, 'history', ['history_id'])
    op.create_unique_constraint(None, 'maintenance', ['maintenance_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'maintenance', type_='unique')
    op.drop_constraint(None, 'history', type_='unique')
    op.drop_constraint(None, 'bike', type_='unique')
    # ### end Alembic commands ###
