"""removed not-null restriction for interval amount and unit in maintenance table

Revision ID: 577a000094df
Revises: 41d9e0fd5fbd
Create Date: 2020-07-13 17:14:51.651638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '577a000094df'
down_revision = '41d9e0fd5fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maintenance', 'interval_amount',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('maintenance', 'interval_unit',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maintenance', 'interval_unit',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)
    op.alter_column('maintenance', 'interval_amount',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
