"""changed JSON field to ARRAY

Revision ID: 59afd48d9690
Revises: e8b596b8161e
Create Date: 2021-01-01 23:04:34.693465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59afd48d9690'
down_revision = 'e8b596b8161e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maintenance', 'tags_default',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.String()),
               postgresql_using="string_to_array(translate(tags_default::text, '[] \"', ''), ',')::character varying[]",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maintenance', 'tags_default',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               postgresql_using="array_to_json(tags_default::character varying[])::json",
               existing_nullable=True)
    # ### end Alembic commands ###
