"""Added the bike_id to the maintenance model as foreign key

Revision ID: 75d584ca4e5d
Revises: d881fab95e36
Create Date: 2020-11-14 22:53:26.970226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75d584ca4e5d'
down_revision = 'd881fab95e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'laptime', ['lap_id'])
    op.add_column('maintenance', sa.Column('bike_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'maintenance', 'bike', ['bike_id'], ['bike_id'])
    op.create_unique_constraint(None, 'session', ['session_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='unique')
    op.drop_constraint(None, 'maintenance', type_='foreignkey')
    op.drop_column('maintenance', 'bike_id')
    op.drop_constraint(None, 'laptime', type_='unique')
    # ### end Alembic commands ###
