"""implemented active column

Revision ID: 834cd47b6e93
Revises: b12b289fc5ac
Create Date: 2021-10-07 19:44:49.012513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '834cd47b6e93'
down_revision = 'b12b289fc5ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tire', sa.Column('active', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'tire', ['tire_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tire', type_='unique')
    op.drop_column('tire', 'active')
    # ### end Alembic commands ###
