"""set column track_layout in the laptime model not nullable

Revision ID: 8c30fd6c02bd
Revises: f332352598ee
Create Date: 2021-01-17 17:17:13.835051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c30fd6c02bd'
down_revision = 'f332352598ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('laptime', 'track_layout',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('laptime', 'track_layout',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
