"""added name to sparepart model and changed column property stock to current_stock

Revision ID: 93ae846289d7
Revises: 6239355ee47c
Create Date: 2020-11-28 21:18:23.100862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ae846289d7'
down_revision = '6239355ee47c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sparepart', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'sparepart', ['sparepart_id'])
    op.create_unique_constraint(None, 'sparepartitem', ['sparepartitem_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sparepartitem', type_='unique')
    op.drop_constraint(None, 'sparepart', type_='unique')
    op.drop_column('sparepart', 'name')
    # ### end Alembic commands ###
