"""added tire schema

Revision ID: b12b289fc5ac
Revises: 8c30fd6c02bd
Create Date: 2021-09-21 19:48:19.533697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b12b289fc5ac'
down_revision = '8c30fd6c02bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tire',
    sa.Column('tire_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('bike_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('rim', sa.String(length=15), nullable=True),
    sa.Column('category', sa.String(length=5), nullable=False),
    sa.Column('manufacturer', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('compound', sa.String(length=10), nullable=True),
    sa.Column('axis', sa.String(length=5), nullable=False),
    sa.Column('dimension', sa.String(length=15), nullable=True),
    sa.Column('dot', sa.String(length=4), nullable=False),
    sa.Column('condition', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('operating_hours', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('datetime_created', sa.DateTime(), nullable=False),
    sa.Column('datetime_last_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bike_id'], ['bike.bike_id'], ),
    sa.PrimaryKeyConstraint('tire_id'),
    sa.UniqueConstraint('tire_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tire')
    # ### end Alembic commands ###
