"""make stock column of the sparepartitemtable not nullable

Revision ID: b5f27fc737f8
Revises: d26f987eae9c
Create Date: 2020-12-19 02:11:25.707475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f27fc737f8'
down_revision = 'd26f987eae9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sparepartitem', 'stock',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sparepartitem', 'stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
