"""remove tire notes

Revision ID: c6ea7844c8b9
Revises: b5f27fc737f8
Create Date: 2020-12-29 11:55:27.335376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ea7844c8b9'
down_revision = 'b5f27fc737f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bike', 'slick_front_notes')
    op.drop_column('bike', 'rain_rear_notes')
    op.drop_column('bike', 'rain_front_notes')
    op.drop_column('bike', 'slick_rear_notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('slick_rear_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('bike', sa.Column('rain_front_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('bike', sa.Column('rain_rear_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('bike', sa.Column('slick_front_notes', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
