"""implemented tag column in history table

Revision ID: c963bcbce405
Revises: 577a000094df
Create Date: 2020-07-20 11:17:31.467714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c963bcbce405'
down_revision = '577a000094df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'tags')
    # ### end Alembic commands ###
