"""added column stock to the sparepartitem and modified the column property current_stock of the sparepart

Revision ID: d26f987eae9c
Revises: 93ae846289d7
Create Date: 2020-12-19 00:26:10.686701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd26f987eae9c'
down_revision = '93ae846289d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sparepartitem', sa.Column('stock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sparepartitem', 'stock')
    # ### end Alembic commands ###
