"""implemented laptime and session model, a session consists of many laptimes

Revision ID: d881fab95e36
Revises: f7574a76a57e
Create Date: 2020-08-20 19:44:40.207017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd881fab95e36'
down_revision = 'f7574a76a57e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('session_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('training_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('setup_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('bike_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('application', sa.String(length=50), nullable=True),
    sa.Column('datetime_created', sa.DateTime(), nullable=False),
    sa.Column('datetime_last_modified', sa.DateTime(), nullable=False),
    sa.Column('datetime_display', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bike_id'], ['bike.bike_id'], ),
    sa.ForeignKeyConstraint(['setup_id'], ['setup.setup_id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['training.training_id'], ),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('laptime',
    sa.Column('lap_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('session_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('lap_no', sa.Integer(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('laptime_seconds', sa.Float(), nullable=False),
    sa.Column('sectors', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('datetime_created', sa.DateTime(), nullable=False),
    sa.Column('datetime_last_modified', sa.DateTime(), nullable=False),
    sa.Column('datetime_display', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ),
    sa.PrimaryKeyConstraint('lap_id'),
    sa.UniqueConstraint('lap_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laptime')
    op.drop_table('session')
    # ### end Alembic commands ###
