"""Added column location to training table

Revision ID: dd0739079388
Revises: 19e2b2f7f1bf
Create Date: 2020-07-03 14:43:48.078485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd0739079388'
down_revision = '19e2b2f7f1bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'setup', ['setup_id'])
    op.add_column('training', sa.Column('location', sa.String(), nullable=False))
    op.alter_column('training', 'weather',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.create_unique_constraint(None, 'training', ['training_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training', type_='unique')
    op.alter_column('training', 'weather',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('training', 'location')
    op.drop_constraint(None, 'setup', type_='unique')
    # ### end Alembic commands ###
