"""added tire note columns in the bike table

Revision ID: e8b596b8161e
Revises: 539dca5534aa
Create Date: 2020-12-29 17:21:48.148564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b596b8161e'
down_revision = '539dca5534aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('rain_front_notes', sa.Text(), nullable=True))
    op.add_column('bike', sa.Column('rain_rear_notes', sa.Text(), nullable=True))
    op.add_column('bike', sa.Column('slick_front_notes', sa.Text(), nullable=True))
    op.add_column('bike', sa.Column('slick_rear_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bike', 'slick_rear_notes')
    op.drop_column('bike', 'slick_front_notes')
    op.drop_column('bike', 'rain_rear_notes')
    op.drop_column('bike', 'rain_front_notes')
    # ### end Alembic commands ###
