"""added column track_layout to the laptime model

Revision ID: f332352598ee
Revises: 17a6500d4803
Create Date: 2021-01-17 17:12:34.160404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f332352598ee'
down_revision = '17a6500d4803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laptime', sa.Column('track_layout', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laptime', 'track_layout')
    # ### end Alembic commands ###
