"""modified names of bike table columns

Revision ID: f7574a76a57e
Revises: 34fffdb29082
Create Date: 2020-08-04 12:14:59.374103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f7574a76a57e'
down_revision = '34fffdb29082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('rain_front_notes', sa.Text(), nullable=True))
    op.add_column('bike', sa.Column('rain_front_pressure', sa.Float(), nullable=True))
    op.add_column('bike', sa.Column('rain_rear_notes', sa.Text(), nullable=True))
    op.add_column('bike', sa.Column('rain_rear_pressure', sa.Float(), nullable=True))
    op.add_column('bike', sa.Column('slick_front_notes', sa.Text(), nullable=True))
    op.add_column('bike', sa.Column('slick_front_pressure', sa.Float(), nullable=True))
    op.add_column('bike', sa.Column('slick_rear_notes', sa.Text(), nullable=True))
    op.add_column('bike', sa.Column('slick_rear_pressure', sa.Float(), nullable=True))
    op.drop_column('bike', 'slick_rear_pressure_base')
    op.drop_column('bike', 'slick_front_pressure_notes')
    op.drop_column('bike', 'rain_front_pressure_base')
    op.drop_column('bike', 'rain_rear_pressure_base')
    op.drop_column('bike', 'slick_front_pressure_base')
    op.drop_column('bike', 'rain_front_pressure_notes')
    op.drop_column('bike', 'rain_rear_pressure_notes')
    op.drop_column('bike', 'slick_rear_pressure_notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('slick_rear_pressure_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('bike', sa.Column('rain_rear_pressure_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('bike', sa.Column('rain_front_pressure_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('bike', sa.Column('slick_front_pressure_base', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('bike', sa.Column('rain_rear_pressure_base', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('bike', sa.Column('rain_front_pressure_base', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('bike', sa.Column('slick_front_pressure_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('bike', sa.Column('slick_rear_pressure_base', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('bike', 'slick_rear_pressure')
    op.drop_column('bike', 'slick_rear_notes')
    op.drop_column('bike', 'slick_front_pressure')
    op.drop_column('bike', 'slick_front_notes')
    op.drop_column('bike', 'rain_rear_pressure')
    op.drop_column('bike', 'rain_rear_notes')
    op.drop_column('bike', 'rain_front_pressure')
    op.drop_column('bike', 'rain_front_notes')
    # ### end Alembic commands ###
