"""implemented default tags column in maintenance table

Revision ID: fa3d2061d14e
Revises: c963bcbce405
Create Date: 2020-07-21 12:52:42.048553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa3d2061d14e'
down_revision = 'c963bcbce405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance', sa.Column('tags_default', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance', 'tags_default')
    # ### end Alembic commands ###
